### ISSUE TITLE
gRPC error when running the code examples on CPU. 

### ISSUE THREAD

**Issue by ZhanqiuHu** [RedisVentures/Redis-Recsys#8]
I was following the notebooks to run the examples, and everything works fine for me when running the Deploying Online Multi-Stage RecSys with Triton Inference Server notebook on GPU. 

```
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
```

However, after I modified the model configuration file to let the ensemble (specifically the user-embedding model and ranking model) run on CPUs, I ran into this error 

```
!python client.py --user 12

[/workspace/online-multi-stage-recsys](https://file+.vscode-resource.vscode-cdn.net/workspace/online-multi-stage-recsys)
Finding recommendations for User 12
Traceback (most recent call last):
  File "/workspace/online-multi-stage-recsys/client.py", line 53, in <module>
    results = triton_client.infer(model_name=args.model_name,
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_client.py", line 1361, in infer
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.10/dist-packages/tritonclient/grpc/_utils.py", line 65, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INTERNAL] in ensemble 'ensemble-model', indices[0] = 3 is not in [0, 3)
	 [[{{function_node __inference__wrapped_model_203518}}{{node encoder/parallel_block/embeddings/user_is_occupied/user_is_occupied/embedding_lookup}}]]
```

Does anyone know what the problem is and how to fix it?

Thanks!

**Comment by Spartee** [comment]
Not sure, this may be a version issue or something with the triton client. I'll ping the Triton team

**Comment by tanmayv25** [comment]
> [StatusCode.INTERNAL] in ensemble 'ensemble-model', indices[0] = 3 is not in [0, 3)

This looks like a model in the pipeline generated an index beyond the acceptable range. Can you verify whether the client is sending valid data?
The issue is most likely coming from the models and computations within it. There might be some small discrepancies when running operations on GPU vs CPU which might be cascading into this error.

**Comment by ZhanqiuHu** [comment]
Hi Tanmay and Sam,

Thanks for getting back to me! The client is sending valid data. The models
that are causing this issue are the user embedding model
<https://github.com/RedisVentures/Redis-Recsys/tree/master/online-multi-stage-recsys/models/1-user-embeddings>
and
the ranking model
<https://github.com/RedisVentures/Redis-Recsys/tree/master/online-multi-stage-recsys/models/5-ranking>,
which are both TensorFlow savedmodels.

Thanks,
Zhanqiu
